# script that checks aspects of the report generated by Source Analyzer
# Author: Chris Curreri

from unittest import TestLoader, TestResult


def test_report():
    return


if __name__ == "__main__":
    test_report()